### PR TITLE
Fix Broken beforeDate and afterDate time filters

### PR DESCRIPTION
**Pull request by igorpojzl**
**Issue Reference this PR resolves**

Broken beforeDate and afterDate time filters #48

### CODE REVIEW

**Comment by igorpojzl** [comment]
@pyrooka Please review.

**Comment by pyrooka** [comment]
Thanks for the fix! One little thing: please try to avoid copying large code blocks if it is not necessary because it makes the review harder.

**Comment by pyrooka** [comment]
Have you tested the other filters? For me, the others look like broken:
image

**Comment by pyrooka** [comment]
MBQL:
`:filter [:and [:= [:field-id 40] [:value Harry {:base_type :type/Text, :special_type :type/Category, :database_type string}]] [:< [:datetime-field [:field-id 43] :default] [:absolute-datetime (t/zoned-date-time 1990-03-31T00:00Z[GMT]) :default]]]`
Native:
`:filters [{:member Characters.birth, :operator beforeDate, :values [1990-03-31T00:00:00Z]}]`

**Pull request merged**
